# Generated by Django 5.1.1 on 2025-09-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
