# Generated by Django 5.1.1 on 2025-09-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_organizer_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='old_cart',
            field=models.TextField(blank=True, null=True),
        ),
    ]
