# Generated by Django 5.1.1 on 2025-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_remove_orderitem_user_orderitem_go_naked'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note_for_seller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
