# Generated by Django 5.1.1 on 2025-08-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0014_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note_for_seller',
            field=models.TextField(blank=True, null=True),
        ),
    ]
