# Generated by Django 5.1.1 on 2025-08-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='experience_videos/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='experiences.experience')),
            ],
        ),
    ]
