# Generated by Django 5.1.1 on 2025-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experience_is_free_alter_experience_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='organizer_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='experience',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
