# Generated by Django 5.1.1 on 2025-09-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_alter_experience_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='experiences.experience'),
        ),
    ]
