# Generated by Django 5.1.1 on 2025-09-16 05:12

import uuid
from django.db import migrations, models

def generate_booking_codes(apps, schema_editor):
    Booking = apps.get_model('experiences', 'Booking')
    for booking in Booking.objects.all():
        booking.booking_code = str(uuid.uuid4())[:8].upper()
        booking.save(update_fields=['booking_code'])

class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_booking_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=20, unique=True, null=True),
        ),
        migrations.RunPython(generate_booking_codes),
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(
                max_length=20,
                choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')],
                default='CONFIRMED',
            ),
        ),
    ]
