# Generated by Django 5.1.1 on 2025-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0010_booking_booking_code_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('CANCELED', 'Canceled'), ('REFUNDED', 'Refunded')], default='BOOKED', max_length=20),
        ),
    ]
